// constants/residentData.js
// Expanded static seed data for the resident My Requests history screen.
// Contains a broader set of request states to exercise all filter tabs
// and request card variants (pending, matched, in_progress, completed).
// Replace with Supabase query when live backend is wired.

export const RESIDENT_REQUESTS = [
  {
    id: 1,
    title:           'Electrical Repair',
    service:         'electrical',
    status:          'matched',
    issue:           'Tripped circuit breaker',
    date:            'March 21, 2026',
    daily_rate:      650,
    worker:          'Juan Dela Cruz',
    address:         'Zone 1, Bulua, CDO',
    budget:          '₱400 – ₱500/day',
    preferred_start: 'Within 3 Days',
    rated:           false,
  },
  {
    id: 2,
    title:           'Kitchen Plumbing',
    service:         'plumbing',
    status:          'completed',
    issue:           'Leaking pipe or faucet',
    date:            'Feb 24, 2026',
    daily_rate:      550,
    worker:          'Pedro Santos',
    address:         'Zone 1, Bulua, CDO',
    budget:          '₱400 – ₱500/day',
    preferred_start: 'Today',
    rated:           false,
  },
  {
    id: 3,
    title:           'Roof Carpentry',
    service:         'carpentry',
    status:          'completed',
    issue:           'Broken furniture',
    date:            'Feb 18, 2026',
    daily_rate:      500,
    worker:          'Ramon Reyes',
    address:         'Zone 1, Bulua, CDO',
    budget:          '₱400 – ₱500/day',
    preferred_start: 'This Week',
    rated:           true,
  },
  {
    id: 4,
    title:           'Cabinet Installation',
    service:         'carpentry',
    status:          'in_progress',
    issue:           'Cabinet installation',
    date:            'Feb 15, 2026',
    daily_rate:      600,
    worker:          'Pedro Santos',
    address:         'Zone 1, Bulua, CDO',
    budget:          '₱500+/day',
    preferred_start: 'Today',
    rated:           false,
  },
  {
    id: 5,
    title:           'Gate Welding',
    service:         'welding',
    status:          'pending',
    issue:           'Gate or fence repair',
    date:            'March 30, 2026',
    daily_rate:      null,
    worker:          null,
    address:         'Zone 1, Bulua, CDO',
    budget:          '₱300 – ₱400/day',
    preferred_start: 'No Rush',
    rated:           false,
  },
  {
    id: 6,
    title:           'Bathroom Tile Repair',
    service:         'mason',
    status:          'completed',
    issue:           'Tile repair or installation',
    date:            'Feb 10, 2026',
    daily_rate:      580,
    worker:          'Mario Bautista',
    address:         'Zone 1, Bulua, CDO',
    budget:          '₱500+/day',
    preferred_start: 'Today',
    rated:           true,
  },
  {
    id: 7,
    title:           'Living Room Plumbing',
    service:         'plumbing',
    status:          'pending',
    issue:           'Clogged drain',
    date:            'April 1, 2026',
    daily_rate:      null,
    worker:          null,
    address:         'Zone 1, Bulua, CDO',
    budget:          'Open / Negotiable',
    preferred_start: 'Within 3 Days',
    rated:           false,
  },
  {
    id: 8,
    title:           'Bedroom Outlet Fix',
    service:         'electrical',
    status:          'completed',
    issue:           'Faulty outlet',
    date:            'Jan 28, 2026',
    daily_rate:      650,
    worker:          'Rosa Lim',
    address:         'Zone 1, Bulua, CDO',
    budget:          '₱400 – ₱500/day',
    preferred_start: 'Today',
    rated:           true,
  },
];