# Generated by Django 6.0.3 on 2026-03-30 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobrequest_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='budget',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='schedule',
            field=models.CharField(choices=[('asap', 'As Soon As Possible'), ('weekdays', 'Weekdays Only'), ('weekends', 'Weekends Only'), ('flexible', 'Flexible / Any Time')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='urgency',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('normal', 'Normal'), ('flexible', 'Flexible')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='availability',
            field=models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekends', 'Weekends'), ('Flexible', 'Flexible'), ('Everyday', 'Everyday')], default='Weekdays', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='barangay_clearance',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='government_id',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='jobs_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.TextField(help_text='e.g., Plumbing, Pipe Fitting, Water Heater'),
        ),
    ]
