# Generated by Django 5.2.12 on 2026-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobrequest_assigned_worker_jobrequest_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
