# Generated by Django 5.2.12 on 2026-05-16 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('verify_worker', 'Verified Worker'), ('reject_worker', 'Rejected Worker'), ('verify_resident', 'Verified Resident'), ('reject_resident', 'Rejected Resident'), ('suspend_user', 'Suspended User'), ('reactivate_user', 'Reactivated User'), ('approve_deletion', 'Approved Account Deletion'), ('reject_deletion', 'Rejected Account Deletion'), ('create_category', 'Created Skill Category'), ('update_category', 'Updated Skill Category'), ('cancel_job', 'Cancelled Job Request'), ('login', 'Admin Login'), ('logout', 'Admin Logout')], max_length=50)),
                ('target_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
