# Generated by Django 5.2.12 on 2026-04-10 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_api', '0001_initial'),
        ('residents', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='workers.workerprofile'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requests', to='workers.skillcategory'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='residents.residentprofile'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='requests_api.jobrequest'),
        ),
        migrations.AddField(
            model_name='rating',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='requests_api.joboffer'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['resident', 'status'], name='job_request_residen_c961f6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['category', 'status'], name='job_request_categor_763515_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['request', 'status'], name='job_offers_request_180e54_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['worker', 'status'], name='job_offers_worker__e39dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user'], name='ratings_rated_u_ba00f7_idx'),
        ),
    ]
