# Generated by Django 5.2.12 on 2026-05-20 04:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_api', '0002_initial'),
        ('workers', '0002_workerprofile_address_lat_workerprofile_address_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional resident note providing supplementary context. Appended to job_type.description before ML vectorization.'),
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Canonical description used as the primary TF-IDF input in the ML matching engine. Include relevant trade keywords.')),
                ('icon', models.CharField(blank=True, help_text="Optional icon name or emoji for the UI tile (e.g. '⚡').", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='workers.skillcategory')),
            ],
            options={
                'db_table': 'job_types',
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job_type',
            field=models.ForeignKey(blank=True, help_text='Job type tile selected by the resident. Drives the TF-IDF query.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requests', to='requests_api.jobtype'),
        ),
    ]
