# Generated by Django 5.2.12 on 2026-05-26 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('government_id', 'Government ID'), ('proof_of_residence', 'Proof of Residence'), ('other', 'Other')], max_length=30)),
                ('storage_url', models.URLField(max_length=1000)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='residents.residentprofile')),
            ],
            options={
                'db_table': 'resident_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
