# Generated by Django 5.2.12 on 2026-04-10 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skill_categories',
            },
        ),
        migrations.CreateModel(
            name='RateBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_bands', to='workers.skillcategory')),
            ],
            options={
                'db_table': 'rate_bands',
                'indexes': [models.Index(fields=['category', 'effective_date'], name='rate_bands_categor_33a12e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('declared_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_experience', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('availability_schedule', models.JSONField(blank=True, default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.skillcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worker_profiles',
                'indexes': [models.Index(fields=['skill_category', 'verification_status'], name='worker_prof_skill_c_583f91_idx'), models.Index(fields=['user'], name='worker_prof_user_id_df2160_idx')],
            },
        ),
    ]
