# Generated by Django 5.2.12 on 2026-05-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='address_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Geocoded latitude of the worker's registered address.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='address_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Geocoded longitude of the worker's registered address.", max_digits=10, null=True),
        ),
    ]
