# Generated by Django 5.2.12 on 2026-05-22 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerprofile_address_lat_workerprofile_address_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_job_types', to='workers.skillcategory')),
            ],
            options={
                'db_table': 'workers_job_types',
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
