# Generated by Django 5.2.12 on 2026-05-22 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='workers.skillcategory'),
        ),
        migrations.AlterModelTable(
            name='jobtype',
            table='job_types',
        ),
    ]
