# Generated by Django 5.2.12 on 2026-05-26 00:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_initial'),
        ('workers', '0004_alter_jobtype_category_alter_jobtype_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('certification', 'Certification'), ('barangay_clearance', 'Barangay Clearance'), ('government_id', 'Government ID'), ('proof_of_residence', 'Proof of Residence')], max_length=30)),
                ('storage_url', models.URLField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='residents.residentprofile')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workers.workerprofile')),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(fields=['worker'], name='documents_worker__576058_idx'), models.Index(fields=['resident'], name='documents_residen_5f26c6_idx')],
            },
        ),
    ]
