# Generated by Django 5.2.12 on 2026-05-26 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('certification', 'Certification'), ('barangay_clearance', 'Barangay Clearance'), ('government_id', 'Government ID'), ('other', 'Other')], max_length=30)),
                ('storage_url', models.URLField(max_length=1000)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workers.workerprofile')),
            ],
            options={
                'db_table': 'worker_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
